### ISSUE TITLE
get_course_by_name in project.py needs implementing 

### ISSUE THREAD

**Issue by audreyannbw** [AAAStrix/ctrl-class#16]
Used in projects.py

**Comment by alexlafroscia** [comment]
~~Does `project.py` refer to a file that's part of your branch?~~

Nevermind, I found it.

Would it be possible to implement [this request](https://github.com/AAAStrix/ctrl-class/blob/add-project-functionality/controllers/projects.py#L28-L29) such that we send the Course Key instead of the name? It's going to be _much_ more efficient to look the course up if we have the key, and it shouldn't be too hard to have the form to create a new project submit the key instead of a string for the name, although that really depends on how you were imaging the "add a new project" form would work.  If you can only add a project from a Course page, or if you select the Course to make a project in from a drop-down menu, using the key shouldn't be too bad.  

My concern is that getting the Course by name has to do a Search (in runtime terms, _some_ kind of `O(N)` operation probably) instead of the key-based lookup which we can assume is going to be much closer to constant time.
